### ISSUE TITLE
Document the programmatic configuration of the DataSources

### ISSUE THREAD

**Issue by helio-frota** [wildfly-swarm/wildfly-swarm-users-guide#2]
example:
https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi-jpa/src/main/java/wildflyswarm/jaxrscdijpa/App.java#L18-L35

**Comment by kenfinnigan** [comment]
Moved to https://issues.jboss.org/browse/SWARM-237
